//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 2 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 2 localization keys.
    struct localizable {
      /// Value: Unable to encode data
      static let encodingError = Rswift.StringResource(key: "encodingError", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Unable to get data
      static let decodingError = Rswift.StringResource(key: "decodingError", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      
      /// Value: Unable to encode data
      static func encodingError(_: Void = ()) -> String {
        return NSLocalizedString("encodingError", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Unable to get data
      static func decodingError(_: Void = ()) -> String {
        return NSLocalizedString("decodingError", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    /// This `R.string.requests` struct is generated, and contains static references to 3 localization keys.
    struct requests {
      /// Value: Audience
      static let audience = Rswift.StringResource(key: "audience", tableName: "Requests", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Authorization
      static let authorization = Rswift.StringResource(key: "authorization", tableName: "Requests", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: User-Agent
      static let userAgent = Rswift.StringResource(key: "userAgent", tableName: "Requests", bundle: R.hostingBundle, locales: [], comment: nil)
      
      /// Value: Audience
      static func audience(_: Void = ()) -> String {
        return NSLocalizedString("audience", tableName: "Requests", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Authorization
      static func authorization(_: Void = ()) -> String {
        return NSLocalizedString("authorization", tableName: "Requests", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: User-Agent
      static func userAgent(_: Void = ()) -> String {
        return NSLocalizedString("userAgent", tableName: "Requests", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try launchScreen.validate()
      try main.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = ViewController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
